name: Test
on:
  push:
  workflow_dispatch:
concurrency: 
  group: test
  cancel-in-progress: true

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: Darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: insightsengineering/pip-action@v2
        with:
          packages: |
            qemu.qmp==0.0.3
      - name: Get paths
        id: get_paths
        run: |
          import os
          relpath = "${{ runner.temp }}" or "./"
          abspath = os.path.abspath(relpath)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f'OUTDIR={abspath}', file=fh)
        shell: python
      - name: Prepare common shell (Windows)
        if: runner.os == 'Windows'
        uses: Vampire/setup-wsl@v2
        with:
          additional-packages:
            ca-certificates
            openssl
            aria2
            p7zip-full
      - name: Prepare common shell (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir bash-redirect
          ln -s $(which bash) bash-redirect/wsl-bash
          echo "$PWD/bash-redirect" >> $GITHUB_PATH
      - name: Prepare common shell (Darwin)
        if: runner.os == 'macOS'
        run: |
          mkdir bash-redirect
          ln -s $(which bash) bash-redirect/wsl-bash
          echo "$PWD/bash-redirect" >> $GITHUB_PATH
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          aria2c --dir="${{ runner.temp }}" https://github.com/physics-enthusiast/qemu-patched-compile/releases/download/qemu-test/qemu-setup.exe
          Start-Process -FilePath '${{ runner.temp }}/qemu-setup.exe' -ArgumentList '/S /D=C:\Program Files\qemu' -NoNewWindow -Wait -PassThru -RedirectStandardOutput output.txt -RedirectStandardError error.txt
          Add-Content $env:GITHUB_PATH "C:\Program Files\qemu"
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install qemu-system
      - name: Install dependencies (Darwin)
        if: runner.os == 'macOS'
        run: |
          brew install qemu --force
      - name: Fetch prebuilt NixOS image manifest
        id: read_manifest
        uses: cityoflosangeles/fetch-latest-github-release@v2.0.3
        with:
          github_token: ${{ github.token }}
          repo_path: "physics-enthusiast/nixos-image"
      - name: Restore cache
        id: restore-cache-image
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/nixos-qcow.7z
          key: ${{ steps.read_manifest.outputs.tag_name }}
      - name: Fetch prebuilt NixOS image
        if: steps.restore-cache-image.outputs.cache-hit != 'true' 
        run: |
          sudo aria2c --dir="$TMPDIR" https://github.com/physics-enthusiast/nixos-image/releases/download/${{ steps.read_manifest.outputs.tag_name }}/nixos-qcow.7z
        shell: wsl-bash {0}
        env:
          WSLENV: GITHUB_OUTPUT/p:TMPDIR/p
          TMPDIR: ${{ runner.temp }}
      - name: Save cache
        id: save-cache-image
        uses: actions/cache/save@v4
        if: steps.restore-cache-image.outputs.cache-hit != 'true'
        with:
          path: ${{ runner.temp }}/nixos-qcow.7z
          key: ${{ steps.read_manifest.outputs.tag_name }}
      - name: Extract image
        run: |
          mkdir $TMPDIR/extraction
          7z e $TMPDIR/nixos-qcow.7z -o"$TMPDIR/extraction"
          mv $TMPDIR/extraction/* $TMPDIR/nixos.qcow2
        shell: wsl-bash {0}
        env:
          WSLENV: GITHUB_OUTPUT/p:TMPDIR/p
          TMPDIR: ${{ runner.temp }}
      - name: Start VM
        run: |
          import os
          import sys
          import asyncio
          import socket
          import base64
          from qemu.qmp import QMPClient
          class CommandError(Exception):
              "Nonzero exit of guest-exec command"
              pass
          cmd = f"qemu-system-x86_64 -nographic -m 4096 -chardev socket,id=qga0,host=localhost,port=9876,server=on -device virtio-serial -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 -fsdev local,security_model=mapped,id=fsdev0,path={os.environ['TMPDIR']}/extraction -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -smp {os.cpu_count()} -nic user -hda {os.environ['TMPDIR']}/nixos.qcow2"
          async def main():
              proc = await asyncio.create_subprocess_shell(cmd)
              qmp = QMPClient()
              qmp.await_greeting = False
              qmp.negotiate = False
              while True:
                  try:
                      qga_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                      qga_sock.connect(('localhost', 9876))
                      break
                  except socket.error:
                      await asyncio.sleep(1) 
              await qmp.connect(qga_sock)
              res = await qmp.execute('guest-ping')
              async def run(cmd, print_output=False, print_error=False):
                  pid = await qmp.execute('guest-exec',{'path':'/run/current-system/sw/bin/bash','arg':['-c', '{}'.format(cmd)],'capture-output':'separated'})
                  res = await qmp.execute('guest-exec-status',pid)
                  while not res['exited']:
                      await asyncio.sleep(1)
                      res = await qmp.execute('guest-exec-status',pid)
                  if res['exitcode'] == 0:
                      if res.has_key('out-data'):
                          output = base64.b64decode(res['out-data']).decode('utf-8')
                          if print_output:
                              print(output)
                          return output
                      if print_output:
                          print('Command succeeded')
                  else:
                      if res.has_key('err-data'): 
                          output = base64.b64decode(res['err-data']).decode('utf-8')
                          if print_error:
                              print(output)
                          raise CommandError(output)
                      raise CommandError('Command failed, no error message produced')
              async def run_force(cmd, print_output=False, print_error=False):
                  while True:
                      try:
                          res = await run(cmd, print_output, print_error)
                          break
                      except:
                          await asyncio.sleep(1)
                  return res
              res = await run_force("systemctl is-system-running", print_output=True, print_error=True)
              await run("mkdir -p /tmp/host_files", print_output=True, print_error=True)
              await run("mount -t 9p -o trans=virtio,version=9p2000.L hostshare /tmp/host_files", print_output=True, print_error=True)
          asyncio.run(main())
        shell: python
        env:
          TMPDIR: ${{ runner.temp }}

          
