name: Test
on:
  push:
concurrency: 
  group: test
  cancel-in-progress: true

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: Darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install QEMU (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install qemu
          Add-Content $env:GITHUB_PATH "C:\Program Files\qemu"
      - name: Install QEMU (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install qemu-system
      - name: Install QEMU (Darwin)
        if: runner.os == 'macOS'
        run: |
          brew install qemu --force
      - name: Fetch prebuilt NixOS image
        run: |
          aria2c https://channels.nixos.org/nixos-23.11/latest-nixos-x86_64-linux.ova -o nixos.ova
      - name: Convert OVA to QCOW2
        run: |
          tar xvf nixos.ova
          qemu-img convert  -f vmdk -O qcow2 latest-nixos-x86_64-linux.vmdk nixos.img
          
