name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          df -h
      - uses: DamianReeves/write-file-action@master
        with:
          path: flake.nix
          write-mode: overwrite
          contents: |
            {
            inputs = {
              nixpkgs.url = "github:physics-enthusiast/nixpkgs/qemu-no-vdso";
              original = {
                url = "github:physics-enthusiast/nixos-image/main";
                inputs.nixpkgs.follows = "nixpkgs";
              };
            };

            outputs = { self, nixpkgs, original }:
            let
              pkgsAarch64 = import nixpkgs { system = "aarch64-linux"; };
              pkgsx86_64 = import nixpkgs { system = "x86_64-linux"; };
            in
              original.outputs // {
              packages."aarch64-linux".default = pkgsAarch64.stdenv.mkDerivation {
                name = "out";

                unpackPhase = "true";

                nativeBuildInputs = [
                  pkgsAarch64.rustc
                ];

                depsBuildBuild = [
                  pkgsAarch64.strace
                ];

                buildPhase = ''
                  echo 'fn main() { }' > main.rs
                  gcc -dumpmachine
                  export QEMU_STRACE=1
                  export RUSTC_LOG=debug
                  #export LD_DEBUG=all
                  declare -p
                  rustc main.rs
                '';

                installPhase = ''
                  cp main $out
                '';
              };
              packages."x86_64-linux".default = pkgsx86_64.fetchFromGitLab {
                owner = "qemu-project";
                repo = "qemu";
                rev = "ebe92db2ccf791208c58d15652f9460a67cc0fdd";
                hash = "sha256-RSsX53RVNfrMrumngj98j4aAN6LkeLcdf8/RSLmn3Cg=";
                fetchSubmodules = true;
              };
              nixosConfigurations.nixos =
                original.nixosConfigurations.nixos-nocloud-x86_64.extendModules {
                  modules = [
                    original.nixosConfigurations.nixos-nocloud-x86_64.config.formatConfigs."qcow"
                    ({ lib, ... }: {
                      options = {
                        fileExtension = lib.mkOption {
                          type = lib.types.str;
                          description = "Declare the path of the wanted file in the output directory";
                          default = "";
                        };
                        formatAttr = lib.mkOption {
                          type = lib.types.str;
                          description = "Declare the default attribute to build";
                        };
                      };
                    })
                    ({ config, pkgs, lib, ... }: {
                      boot = {
                        kernelPackages = pkgs.linuxPackages_latest;
                        binfmt = { 
                          emulatedSystems = [ "aarch64-linux" "armv7l-linux" ];
                          preferStaticEmulators = true;
                        };
                      };
                    })
                  ];
                };
              };
            }
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
      - name: Setup Binfmt
        uses: docker/setup-qemu-action@v3
        with:
          image: 	tonistiigi/binfmt:desktop-master
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
      - run: |
          cat /etc/nix/nix.conf
          nix build --no-link .#packages.x86_64-linux.default
          nix build --print-build-logs --no-link .#packages.aarch64-linux.default
      - uses: catchpoint/workflow-telemetry-action@master
      - uses: physics-enthusiast/nixos-run-action@main
        id: rebuild
        with:
          filesize: 40G
          memory: 16G
          image-path: /mnt/nixos.qcow2
          cmd: |
            nix build --no-link --log-lines 100 "/tmp/mnt"#nixosConfigurations.nixos.config.system.build.toplevel
            sudo nixos-rebuild boot --max-jobs auto --cores 2 --flake '/tmp/mnt#nixos'
      - uses: physics-enthusiast/nixos-run-action@main
        with:
          filesize: 40G
          memory: 16G
          image-path: /mnt/nixos.qcow2
          cmd: |
            nix build --print-build-logs --no-link /tmp/mnt#packages.aarch64-linux.default

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DamianReeves/write-file-action@master
        with:
          path: flake.nix
          write-mode: overwrite
          contents: |
            {
              inputs = {
                nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
              };
              outputs = { self, nixpkgs }:
              let
                pkgs = import nixpkgs { system = "x86_64-linux"; };
              in
              {
                packages."x86_64-linux".default = pkgs.gcc6Stdenv.mkDerivation {
                  name = "frankenlibc";
                  src = pkgs.fetchFromGitHub {
                    owner = "physics-enthusiast";
                    repo = "frankenlibc";
                    rev = "78c8418b08188b7aa7568cde614fc121f155b969";
                    fetchSubmodules = true;
                    sha256 = "sha256-vH3AhWkEMB0yKbr66imNBnUpR6c1bLwBsacDC7GDGVw=";
                  };

                  buildInputs = [ pkgs.stdenv.cc.libc pkgs.stdenv.cc.libc.static pkgs.zlib pkgs.which ];
                  
                  postPatch = ''
                    patchShebangs --build ./
                    substituteInPlace build.sh \
                      --replace-fail '/bin/echo' 'echo' \
                      --replace-fail '#!/bin/sh' '#!${pkgs.stdenv.shell}'
                    substituteInPlace src/build.sh \
                      --replace-fail '/bin/pwd' 'pwd'
                  '';
                };
              };
            }
      - run: |
          nix build -L --show-trace .#packages.x86_64-linux.default
