name: Test
on:
  push:
  workflow_dispatch:
concurrency: 
  group: test
  cancel-in-progress: true

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: Darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'Windows'
        uses: Vampire/setup-wsl@v2
      - name: Install Nix
        run: |
          uname
          bash <(curl -L https://nixos.org/nix/install)
        shell: wsl-bash
          
