name: Test
on:
  push:
  workflow_dispatch:
concurrency: 
  group: test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: DamianReeves/write-file-action@master
        with:
          path: flake.nix
          contents: |
            {
            inputs = {
              original.url = "github:physics-enthusiast/nixos-image/main?dir=nocloud";
              nixpkgs.follows = "original/nixpkgs";
            };

            outputs = { self, nixpkgs, original }:
              original.outputs // {
              nixosConfigurations.nixos =
                original.nixosConfigurations.nixos.extendModules {
                  modules = [
                    original.nixosConfigurations.nixos.config.formatConfigs."qcow"
                    ({ config, pkgs, lib, ... }: {
                      boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
                    })
                    ({ lib, ... }: {
                      options = {
                        fileExtension = lib.mkOption {
                          type = lib.types.str;
                          description = "Declare the path of the wanted file in the output directory";
                          default = "";
                        };
                        formatAttr = lib.mkOption {
                          type = lib.types.str;
                          description = "Declare the default attribute to build";
                        };
                      };
                    })
                  ];
                };
              };
            }
          write-mode: overwrite
      - uses: physics-enthusiast/nixos-run-action@main
        with:
          cmd: |
            nixos-rebuild switch --flake '/tmp/mnt#nixos'

          
