name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: DamianReeves/write-file-action@master
        with:
          path: flake.nix
          write-mode: overwrite
          contents: |
            {
            inputs = {
              nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
              original = {
                url = "github:physics-enthusiast/nixos-image/main";
                inputs.nixpkgs.follows = "nixpkgs";
              };
            };
            outputs = { self, nixpkgs, original }:
              original.outputs // {
              nixosConfigurations.nixos =
                original.nixosConfigurations.nixos-nocloud-x86_64.extendModules {
                  modules = [
                    original.nixosConfigurations.nixos.config.formatConfigs."qcow"
                    ({ lib, ... }: {
                      options = {
                        fileExtension = lib.mkOption {
                          type = lib.types.str;
                          description = "Declare the path of the wanted file in the output directory";
                          default = "";
                        };
                        formatAttr = lib.mkOption {
                          type = lib.types.str;
                          description = "Declare the default attribute to build";
                        };
                      };
                    })
                    ({ config, pkgs, lib, ... }: {
                      boot.kernelPackages = pkgs.linuxPackages_latest;
                    })
                  ];
                };
              };
            }
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
      - uses: catchpoint/workflow-telemetry-action@master
      - uses: physics-enthusiast/nixos-run-action@main
        with:
          filesize: 40G
          memory: 16G
          image-path: /mnt/nixos.qcow2
          cmd: |
            sudo nixos-rebuild switch --max-jobs auto --cores 1 --flake '/tmp/mnt#nixos'
            uname -a

          
