name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
      - uses: catchpoint/workflow-telemetry-action@master
      - uses: physics-enthusiast/nixos-run-action@main
        with:
          filesize: 40G
          memory: 16G
          image-path: /mnt/nixos.qcow2
          cmd: |
            uname -a

          
