name: Test
on:
  push:
concurrency: 
  group: test
  cancel-in-progress: true

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: Darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install QEMU (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install qemu
          Add-Content $env:GITHUB_PATH "C:\Program Files\qemu"
      - name: Install QEMU (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install qemu-system
      - name: Install QEMU (Darwin)
        if: runner.os == 'macOS'
        run: |
          brew install qemu --force
      - name: Fetch prebuilt NixOS image
        run: |
          aria2c https://channels.nixos.org/nixos-23.11/latest-nixos-minimal-x86_64-linux.iso -o nixos.iso
      - name: Convert ISO to QCOW2
        run: |
          qemu-img convert -O qcow2 nixos.iso nixos.img
      - name: Start the VM
        run: |
          qemu-system-x86_64 -append 'console=ttyS0' -nographic -serial mon:stdio -drive format=qcow2,file=nixos.img
          
