name: Test
on:
  push:
  workflow_dispatch:
concurrency: 
  group: test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: physics-enthusiast/nixos-run-action@main
        with:
          cmd: |
            uname
          debug: true

          
