name: Test
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: |
          sudo apt-get -y install qemu-system
      - run: |
          qemu --help

  macos:
    runs-on: macos-latest
    steps:
      - name: Install QEMU
        run: |
          brew install qemu
      - run: |
          qemu --help

  windows:
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: |
          choco install qemu
      - run: |
          qemu --help
