name: Test
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: |
          sudo apt-get -y install qemu-system
      - run: |
          qemu-system-x86_64 --help

  macos:
    runs-on: macos-latest
    steps:
      - run: |
          qemu-system-x86_64 --help

  windows:
    runs-on: windows-latest
    steps:
      - uses: MinoruSekine/setup-scoop@v2
      - name: Install QEMU
        run: |
          choco install qemu
          [Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\qemu", "Machine")
      - run: |
          qemu-system-x86_64 --help
