name: Test
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: |
          sudo apt-get -y install qemu-system

  macos:
    runs-on: macos-latest
    steps:
      - name: Install QEMU
        run: |
          brew install qemu
  
  windows:
    runs-on: windows-latest
    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Install QEMU
        run: |
          winget install --id=SoftwareFreedomConservancy.QEMU  -e
