name: Test
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: |
          sudo apt-get -y install qemu-system
      - run: |
          qemu-system-x86_64 --help

  macos:
    runs-on: macos-latest
    steps:
      - run: |
          qemu-system-x86_64 --help

  windows:
    runs-on: windows-latest
    steps:
      - uses: MinoruSekine/setup-scoop@v2
      - name: Install QEMU
        run: |
          scoop install qemu
          $env:Path = ($env:Path + '~\scoop\apps\qemu\8.2.0') -join ';'
      - run: |
          qemu-system-x86_64 --help
